# Generated by Django 3.2.9 on 2022-01-07 17:23

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', tinymce.models.HTMLField(null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', tinymce.models.HTMLField()),
                ('issue_picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('make', models.CharField(choices=[('Toyota', 'Toyota'), ('Nissan', 'Nissan'), ('Subaru', 'Subaru'), ('Mitsubishi', 'Mitsubishi'), ('Mercedes', 'Mercedes Benz'), ('BMW', 'BMW'), ('Audi', 'Audi'), ('Volkswagen', 'Volkswagen'), ('Honda', 'Honda'), ('Land Rover', 'Land Rover'), ('Ford', 'Ford')], default='Toyota', max_length=60, null=True)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField(choices=[(2021, '2021'), (2020, '2020'), (2019, '2019'), (2018, '2018'), (2017, '2017'), (2016, '2016'), (2015, '2015'), (2014, '2014'), (2013, '2013'), (2012, '2012'), (2011, '2011'), (2010, '2010'), (2009, '2009'), (2008, '2008'), (2007, '2007'), (2006, '2006'), (2005, '2005'), (2004, '2004'), (2003, '2003'), (2002, '2002'), (2001, '2001'), (2000, '2000'), (1999, '1999'), (1998, '1998'), (1997, '1997')])),
                ('posted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poste', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('make', models.CharField(choices=[('Toyota', 'Toyota'), ('Nissan', 'Nissan'), ('Subaru', 'Subaru'), ('Mitsubishi', 'Mitsubishi'), ('Mercedes', 'Mercedes Benz'), ('BMW', 'BMW'), ('Audi', 'Audi'), ('Volkswagen', 'Volkswagen'), ('Honda', 'Honda'), ('Land Rover', 'Land Rover'), ('Ford', 'Ford')], default='Toyota', max_length=60, null=True)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField(choices=[(2021, '2021'), (2020, '2020'), (2019, '2019'), (2018, '2018'), (2017, '2017'), (2016, '2016'), (2015, '2015'), (2014, '2014'), (2013, '2013'), (2012, '2012'), (2011, '2011'), (2010, '2010'), (2009, '2009'), (2008, '2008'), (2007, '2007'), (2006, '2006'), (2005, '2005'), (2004, '2004'), (2003, '2003'), (2002, '2002'), (2001, '2001'), (2000, '2000'), (1999, '1999'), (1998, '1998'), (1997, '1997')])),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default='Automatic', max_length=60, null=True)),
                ('description', models.CharField(max_length=250)),
                ('price', models.IntegerField(null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', tinymce.models.HTMLField()),
                ('location', models.CharField(max_length=60, null=True)),
                ('schedule_time', models.DateTimeField(null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('advice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.advice')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.CharField(max_length=250)),
                ('mobile_number', models.IntegerField(blank=True)),
                ('email', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('Car-Owner', 'Car Owner'), ('Mechanic/Garage', 'Mechanic/Garage'), ('Spareparts-Retailer', 'Spare Parts Retailer')], default='Car-Owner', max_length=60)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
