# Generated by Django 3.2.9 on 2022-01-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='transmission',
        ),
    ]
