# Generated by Django 3.2.9 on 2022-01-10 12:07

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_remove_sale_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='picture2',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='picture3',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
