# Generated by Django 3.2.9 on 2022-01-10 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20220110_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cc',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
