# Generated by Django 3.2.9 on 2022-01-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_sale_cc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='cc',
            new_name='engine_size',
        ),
    ]
